name: CI Pipeline

on:
  push:
    branches: [ main, dev, add-github-ci ]
  pull_request:
    branches: [ main, dev, add-github-ci ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build
      run: mvn -B package --file medved/pom.xml
    - name: Test
      run: mvn -T1C -B --update-snapshots --file medved/pom.xml verify