name: CI Pipeline

on:
  pull_request:
    branches: [ main, dev, add-github-ci ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        
    - name: Test
      run: cd medved
      run: mvn test
